abstract: ~
author: 'Ton Voon C<ton.voon@altinity.com>'
build_requires:
  Test::More: 0.42
distribution_type: module
generated_by: Module::Install version 0.64
license: gpl
name: Algorith-Closest-NetworkAddress
no_index:
  directory:
    - inc
    - t
requires:
  Class::Struct: 0
  perl: 5.8.4
version: 0.1
